### ISSUE TITLE
Invalid type for parameter registryIds[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>

### ISSUE THREAD

**Issue by connatix-cradulescu** [onfido/ecr-mirror#3]
cr-mirror copy "istio/proxyv2:1.7.*" 775235277044.dkr.ecr.us-east-2.amazonaws.com/istio/proxyv2
Traceback (most recent call last):
  File "/home/cradulescu/.local/bin/ecr-mirror", line 11, in <module>
    sys.exit(cli())
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/ecr_mirror/__init__.py", line 81, in copy
    copy_repositories(ctx.obj.client, ctx.obj.registry_id, repositories)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/ecr_mirror/__init__.py", line 114, in copy_repositories
    token = ecr_login(client, registry_id)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/ecr_mirror/__init__.py", line 102, in ecr_login
    auth_response = client.get_authorization_token(registryIds=[registry_id])
  File "/home/cradulescu/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/cradulescu/.local/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter registryIds[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>

**Comment by xenji** [comment]
The registry-id cli parameter seems to be mandatory. Passing it to the command solved it for me.

`ecr-mirror --registry-id <account> copy "istio/proxyv2:1.7.* "<account>.dkr.ecr.us-east-2.amazonaws.com/istio/proxyv2"`
